import Foundation

/// Lo que contesta GET /api/dashboard: un año ya agregado por server.py.
/// La app no suma nada por su cuenta — la misma regla que el cliente web:
/// toda la aritmética vive en el servidor y los clientes solo pintan.
struct DashboardResponse: Decodable {
    let ok: Bool
    let years: [String]
    let year: String
    /// var: el demo edita en memoria y DemoMath re-agrega estas piezas.
    var months: [MonthSummary]
    var annual: AnnualSummary?
}

/// mobile/dashboard.json: todos los años ya calculados por el servidor y
/// sincronizados por iCloud. Cada entrada es la misma respuesta de
/// /api/dashboard, así que el resto de la app no distingue la fuente.
struct MobileSnapshot: Decodable {
    let generatedAt: String?
    let years: [String]
    let dashboards: [String: DashboardResponse]
    /// El dataset de muestra: enseñar la app sin enseñar las finanzas.
    let demo: SnapshotDataset?
    /// El catálogo compartido de categorías, para el selector del modal de
    /// edición. Opcional: un snapshot viejo simplemente no lo trae.
    let categories: [String]?
    /// Las deudas activas del dataset, para el selector de abonos.
    let debts: [DebtOption]?
    /// El módulo de deudas del demo, ya calculado.
    let debtsDetail: [DebtDetail]?
    /// El plan alimentario del demo, ya resuelto.
    let nutrition: NutritionSnapshot?
}

struct SnapshotDataset: Decodable {
    let years: [String]
    let dashboards: [String: DashboardResponse]
}

/// mobile/manifest.json: el índice del snapshot partido por año — qué años
/// hay, el catálogo de categorías y el sello de cada año. Con esto la app
/// decide qué archivo abrir sin descargar ni decodificar nada grande.
struct SnapshotManifest: Decodable {
    let generatedAt: String?
    let years: [String]
    let categories: [String]?
    /// Las deudas activas, para el selector de abonos del editor.
    let debts: [DebtOption]?
    let yearStamps: [String: String]?
}

struct AnnualSummary: Decodable {
    let incomeCop: Double
    let incomeUsd: Double
    var totalOutcomes: Double
    var free: Double
    var averageFree: Double
    let averageFx: Double
    /// "36 categorías registradas": el catálogo compartido, no las usadas.
    let categoriesCount: Int?
    var byType: [String: Double]
    var displayTypes: [String: Double]
    var byCategory: [CategoryTotal]
    var totals: [String: Money]
}

struct Money: Decodable {
    let cop: Double
    let usd: Double
}

struct CategoryTotal: Decodable, Identifiable {
    let category: String
    let total: Double
    var id: String { category }
}

struct MonthSummary: Decodable, Identifiable {
    let index: Int
    let folder: String
    var incomeCop: Double
    var incomeUsd: Double
    var usdCop: Double
    var totalOutcomes: Double
    var paidOutcomes: Double
    var free: Double
    /// Opcionales por si contesta un servidor viejo: mejor una tabla con
    /// filas de menos que una pantalla en blanco (misma decisión que load.ts).
    var afterPaid: Double?
    var summaryRows: [SummaryRow]?
    var byType: [String: Double]
    var displayTypes: [String: Double]
    var byCategory: [CategoryTotal]
    var entries: [Entry]
    var incomes: [Income]
    /// A qué archivo escribe cada tipo — lo que un movimiento nuevo necesita
    /// cuando el mes aún no tiene ninguno de dónde copiar la ruta.
    let sourcePathByType: [String: String]?

    var id: Int { index }
    var rows: [SummaryRow] { summaryRows ?? [] }
}

struct SummaryRow: Decodable, Identifiable {
    let label: String
    let cop: Double
    let usd: Double
    let ratio: Double
    var id: String { label }
}

struct Entry: Decodable, Identifiable {
    var id = UUID()
    var description: String?
    var category: String?
    var amountCop: Double
    var amountUsd: Double?
    var type: String?
    var paid: Bool?
    /// La bandera vieja de pagado, presente en archivos anteriores.
    let active: Bool?
    /// De dónde salió el movimiento — lo que el buzón necesita para pedirle
    /// al servidor del Mac que lo cambie.
    let sourcePath: String?
    let sourceIndex: Int?
    /// El id permanente y numérico que el servidor le asigna: encuentra el
    /// movimiento aunque la lista se reordene.
    let entryId: Int?
    /// true en las cuotas que nacen de una deuda: de esas solo se puede
    /// tocar el pagado — la edición vive en la deuda.
    let autoGenerated: Bool?
    /// A qué deudas abona este movimiento, y la marca de abono extra — lo
    /// que la web pone cuando el tipo es deudas y se eligen deudas.
    var linkedDebts: [String]?
    var extraPayment: Bool?
    /// El rastro que el servidor guarda con cada edición, más los sellos de
    /// vida del movimiento. Opcionales: archivos viejos no los traen.
    let createdAt: String?
    let updatedAt: String?
    let history: [HistoryEvent]?

    var isPaid: Bool { paid ?? active ?? false }

    private enum CodingKeys: String, CodingKey {
        case description, category, amountCop, amountUsd, type, paid, active
        case sourcePath, sourceIndex, autoGenerated
        case linkedDebts, extraPayment
        case createdAt, updatedAt, history
        case entryId = "id"
    }
}

/// Una deuda activa, en lo mínimo que el selector de abonos necesita. Viaja
/// en el manifiesto (y dentro del demo empacado).
struct DebtOption: Decodable, Identifiable {
    let id: String
    let name: String
    /// Lo que le queda por pagar, cuando se sabe. El manifiesto solo trae id y
    /// nombre; el detalle de deudas sí lo sabe, y de ahí se arma la lista que
    /// ve el editor — que necesita el saldo para no dejar abonar de más.
    var remainingBalance: Double?

    init(id: String, name: String, remainingBalance: Double? = nil) {
        self.id = id
        self.name = name
        self.remainingBalance = remainingBalance
    }
}

/// mobile/nutrition.json: el plan alimentario con la semana ya resuelta y la
/// lista de compras ya sumada. Como en deudas, el teléfono no calcula nada:
/// solo pinta lo que el servidor dejó escrito.
struct NutritionSnapshot: Decodable {
    let generatedAt: String?
    /// A qué archivo apuntan el dado y las exclusiones.
    var planPath = ""
    var ingredients: [PlanIngredient] = []
    var week: [PlanDay] = []
    var catalog: [String: [PlannedMeal]] = [:]
    /// Pares [título, texto], tal como los guarda el plan.
    var groundRules: [[String]] = []
    var condimentsYes = ""
    var condimentsNo = ""
    var excludedIngredients: [String] = []
    var shopping: ShoppingList?

    private enum CodingKeys: String, CodingKey {
        case generatedAt, planPath, ingredients, week, catalog, groundRules
        case condimentsYes, condimentsNo, excludedIngredients, shopping
    }

    /// A mano y no sintetizado: Decodable exige la clave aunque la propiedad
    /// tenga valor por defecto, y un dataset sin plan alimentario manda un
    /// objeto vacío. Sin esto, no tener plan sería un error de decodificación
    /// en vez de una sección vacía.
    init(from decoder: Decoder) throws {
        let box = try decoder.container(keyedBy: CodingKeys.self)
        generatedAt = try box.decodeIfPresent(String.self, forKey: .generatedAt)
        planPath = try box.decodeIfPresent(String.self, forKey: .planPath) ?? ""
        ingredients = try box.decodeIfPresent([PlanIngredient].self, forKey: .ingredients) ?? []
        week = try box.decodeIfPresent([PlanDay].self, forKey: .week) ?? []
        catalog = try box.decodeIfPresent([String: [PlannedMeal]].self, forKey: .catalog) ?? [:]
        groundRules = try box.decodeIfPresent([[String]].self, forKey: .groundRules) ?? []
        condimentsYes = try box.decodeIfPresent(String.self, forKey: .condimentsYes) ?? ""
        condimentsNo = try box.decodeIfPresent(String.self, forKey: .condimentsNo) ?? ""
        excludedIngredients = try box.decodeIfPresent([String].self, forKey: .excludedIngredients) ?? []
        shopping = try box.decodeIfPresent(ShoppingList.self, forKey: .shopping)
    }

    /// Sin plan que mostrar.
    var isEmpty: Bool { week.isEmpty && groundRules.isEmpty && (shopping?.lines.isEmpty ?? true) }

    /// Las comidas de un tipo, en el orden del catálogo.
    func catalog(for slot: MealSlot) -> [PlannedMeal] {
        catalog[slot.rawValue] ?? []
    }
}

/// Los cuatro momentos del día, en el orden en que se comen.
enum MealSlot: String, CaseIterable, Identifiable {
    case breakfast, lunch, snack, dinner

    var id: String { rawValue }

    var label: String {
        switch self {
        case .breakfast: return "Desayuno"
        case .lunch: return "Almuerzo"
        case .snack: return "Snack"
        case .dinner: return "Cena"
        }
    }

    var plural: String {
        switch self {
        case .breakfast: return "Desayunos"
        case .lunch: return "Almuerzos"
        case .snack: return "Snacks"
        case .dinner: return "Cenas"
        }
    }

    var icon: String {
        switch self {
        case .breakfast: return "sun.horizon"
        case .lunch: return "fork.knife"
        case .snack: return "leaf"
        case .dinner: return "moon"
        }
    }
}

struct PlanIngredient: Decodable, Identifiable {
    let id: String
    let name: String
    let labels: [String]
    let store: String

    /// La etiqueta con la que se agrupa en la pantalla de exclusiones.
    var mainLabel: String { labels.first ?? "Sin categoría" }
}

struct PlanDay: Decodable, Identifiable {
    let day: String
    let meals: [PlannedMeal]

    var id: String { day }
    /// Lo que cuesta el día: la suma de sus comidas.
    var cost: Double { meals.reduce(0) { $0 + $1.cost } }
}

struct PlannedMeal: Decodable, Identifiable {
    let slot: String
    let id: String
    let name: String
    let description: String
    let cost: Double

    var mealSlot: MealSlot? { MealSlot(rawValue: slot) }
}

struct ShoppingList: Decodable {
    let lines: [ShoppingLine]
    let total: Double
    let weeklyCost: Double
    let dailyAverage: Double
    let assignedMeals: Int
    let totalSlots: Int

    /// Agrupada por tienda, que es como se compra.
    var byStore: [(store: String, lines: [ShoppingLine])] {
        var order: [String] = []
        var grouped: [String: [ShoppingLine]] = [:]
        for line in lines {
            let store = line.store.isEmpty ? "Sin tienda" : line.store
            if grouped[store] == nil { order.append(store) }
            grouped[store, default: []].append(line)
        }
        return order.map { ($0, grouped[$0] ?? []) }
    }
}

struct ShoppingLine: Decodable, Identifiable {
    let id: String
    let name: String
    let unit: String
    let category: String
    let store: String
    let qty: Double
    let price: Double
    let total: Double
}

/// mobile/debts.json: las deudas con su plan ya calculado por el servidor —
/// lo mismo que contesta /api/debts/detail. El teléfono solo pinta.
struct DebtsSnapshot: Decodable {
    let generatedAt: String?
    /// A qué archivo apunta finalizar una deuda.
    let path: String?
    let debts: [DebtDetail]
}

/// El nombre de una deuda: {"es","en"} en los archivos actuales, o texto
/// plano en los viejos.
enum DebtName: Decodable {
    case localized([String: String])
    case plain(String)

    init(from decoder: Decoder) throws {
        let container = try decoder.singleValueContainer()
        if let names = try? container.decode([String: String].self) {
            self = .localized(names)
        } else {
            self = .plain((try? container.decode(String.self)) ?? "")
        }
    }

    var display: String {
        switch self {
        case .localized(let names):
            return names["es"] ?? names["en"] ?? names.values.first ?? "Deuda"
        case .plain(let name):
            return name.isEmpty ? "Deuda" : name
        }
    }
}

struct DebtDetail: Decodable, Identifiable {
    let id: String
    let name: DebtName?
    let financedCapital: Double
    let annualInterestRate: Double
    let monthlyPayment: Double
    let installment: Double?
    let termMonths: Int
    let effectiveTermMonths: Int?
    let paidInstallments: Int
    let remainingInstallments: Int
    let remainingBalance: Double
    /// Capital pagado sobre capital financiado, 0–100 — la misma medida
    /// de la web, que un plan acortado por abonos sí puede llevar al 100.
    let progress: Double
    let totalInterest: Double
    let total: Double
    let schedule: [DebtPeriod]

    var displayName: String { name?.display ?? "Deuda" }
}

/// Una cuota del plan. El período 0 es el arranque: ahí viven los abonos
/// hechos antes de la primera cuota.
struct DebtPeriod: Decodable, Identifiable {
    let period: Int
    let installment: Double
    let interest: Double
    let principal: Double
    let extraPayment: Double
    let actualPayment: Double
    let totalPayment: Double
    let paid: Bool
    let balance: Double
    let monthIndex: Int?
    let year: Int?

    var id: Int { period }
}

/// Una edición del histórico: cuándo, desde dónde, y qué campos cambiaron.
struct HistoryEvent: Decodable, Identifiable {
    var id = UUID()
    let changedAt: String?
    let changedBy: String?
    let changes: [String: FieldChange]?

    private enum CodingKeys: String, CodingKey {
        case changedAt, changedBy, changes
    }

    struct FieldChange: Decodable {
        let from: LooseValue?
        let to: LooseValue?
    }
}

/// Un valor del histórico tal como venga: texto, número o bandera.
enum LooseValue: Decodable {
    case text(String)
    case number(Double)
    case flag(Bool)

    init(from decoder: Decoder) throws {
        let container = try decoder.singleValueContainer()
        if let flag = try? container.decode(Bool.self) {
            self = .flag(flag)
        } else if let number = try? container.decode(Double.self) {
            self = .number(number)
        } else {
            self = .text(try container.decode(String.self))
        }
    }

    /// Cómo se enseña en la hoja de histórico.
    var display: String {
        switch self {
        case .text(let value): return value.isEmpty ? "—" : value
        case .number(let value): return Format.copPlain(value)
        case .flag(let value): return value ? "Sí" : "No"
        }
    }
}

struct Income: Decodable, Identifiable {
    var id = UUID()
    let description: String?
    let amountUsd: Double?
    let usdCop: Double?
    let amountCop: Double?
    var received: Bool?
    /// Dónde vive, para poder marcarlo recibido desde aquí. La API de ingresos
    /// direcciona por archivo, mes y posición — no hay id permanente.
    let sourcePath: String?
    let sourceIndex: Int?
    let monthIndex: Int?

    private enum CodingKeys: String, CodingKey {
        case description, amountUsd, usdCop, amountCop, received
        case sourcePath, sourceIndex, monthIndex
    }
}

/// La aritmética del demo — la única excepción a "toda la aritmética vive en
/// el servidor". El demo va empacado en la app y no tiene Mac atrás, así que
/// editar un movimiento re-agrega aquí el mes y el anual, espejando
/// _summarize_month y _build_dashboard de server.py con sus mismos redondeos
/// (display_cop / display_usd). Solo el demo pasa por aquí; el live sigue
/// pintando lo que el servidor calculó.
enum DemoMath {
    /// normalizeCop del servidor: pesos enteros, mitades hacia arriba.
    private static func displayCop(_ value: Double) -> Double {
        guard value.isFinite, abs(value) >= 0.5 else { return 0 }
        return (value + 0.5).rounded(.down)
    }

    /// normalizeUsd: dos decimales, mitades hacia arriba como JavaScript.
    private static func displayUsd(_ value: Double) -> Double {
        guard value.isFinite, abs(value) >= 0.005 else { return 0 }
        return (value * 100 + 0.5).rounded(.down) / 100
    }

    /// Aplica los cambios (las mismas claves que viajan al buzón del live:
    /// description, category, target_type, amount_cop, paid) y devuelve la
    /// respuesta con el mes tocado y el anual ya re-agregados.
    /// El recibido de un ingreso en el demo. Sí mueve totales: al mes solo le
    /// suman los ingresos recibidos, igual que en _recompute_income_month.
    static func applyingReceived(
        _ received: Bool,
        to income: Income,
        in response: DashboardResponse
    ) -> DashboardResponse {
        editingIncomes(of: income, in: response) { incomes, position in
            incomes[position].received = received
        }
    }

    /// Crear o editar un ingreso en el demo. Con `income` nil es uno nuevo, al
    /// final del mes que se está mirando.
    static func savingIncome(
        _ fields: [String: Outbox.PendingValue],
        to income: Income?,
        monthIndex: Int,
        in response: DashboardResponse
    ) -> DashboardResponse {
        if let income {
            return editingIncomes(of: income, in: response) { incomes, position in
                incomes[position] = applied(fields, to: incomes[position])
            }
        }
        guard let slot = response.months.firstIndex(where: { $0.index == monthIndex }) else {
            return response
        }
        var updated = response
        let blank = Income(
            description: "", amountUsd: 0, usdCop: 0, amountCop: 0, received: false,
            sourcePath: updated.months[slot].incomes.first?.sourcePath,
            // Va al final: es donde lo pone el servidor, y el índice real llega
            // con el próximo snapshot de todos modos.
            sourceIndex: updated.months[slot].incomes.count,
            monthIndex: monthIndex
        )
        updated.months[slot].incomes.append(applied(fields, to: blank))
        recompute(&updated, at: slot)
        return updated
    }

    static func deletingIncome(_ income: Income, in response: DashboardResponse) -> DashboardResponse {
        editingIncomes(of: income, in: response) { incomes, position in
            incomes.remove(at: position)
        }
    }

    /// Encuentra el mes del ingreso, deja que lo toquen y re-agrega.
    private static func editingIncomes(
        of income: Income,
        in response: DashboardResponse,
        _ change: (inout [Income], Int) -> Void
    ) -> DashboardResponse {
        var updated = response
        for slot in updated.months.indices {
            guard let position = updated.months[slot].incomes.firstIndex(where: {
                $0.sourcePath == income.sourcePath && $0.sourceIndex == income.sourceIndex
            }) else { continue }
            change(&updated.months[slot].incomes, position)
            recompute(&updated, at: slot)
            return updated
        }
        return response
    }

    /// Los campos del editor sobre un ingreso. Cuando falta uno de los tres
    /// montos se deriva de los otros dos, como _normalize_new_income_entry.
    private static func applied(
        _ fields: [String: Outbox.PendingValue],
        to income: Income
    ) -> Income {
        func number(_ key: String) -> Double? {
            if case .number(let value)? = fields[key] { return value }
            return nil
        }
        var text = income.description
        if case .text(let value)? = fields["description"] { text = value }
        var received = income.received ?? false
        if case .flag(let value)? = fields["received"] { received = value }

        let usd = number("amount_usd") ?? income.amountUsd ?? 0
        let rate = number("usd_cop") ?? income.usdCop ?? 0
        let cop: Double
        if let given = number("amount_cop") {
            cop = given
        } else if fields["amount_usd"] != nil || fields["usd_cop"] != nil {
            cop = round3(usd * rate)
        } else {
            cop = income.amountCop ?? 0
        }

        return Income(
            id: income.id, description: text, amountUsd: usd, usdCop: rate,
            amountCop: cop, received: received,
            sourcePath: income.sourcePath, sourceIndex: income.sourceIndex,
            monthIndex: income.monthIndex
        )
    }

    /// _recompute_income_month y detrás el resumen del mes y el anual: al mes
    /// solo le suman los ingresos recibidos, y su tasa sale de esos dos totales.
    private static func recompute(_ response: inout DashboardResponse, at slot: Int) {
        let received = response.months[slot].incomes.filter { $0.received ?? false }
        let usd = round3(received.reduce(0) { $0 + ($1.amountUsd ?? 0) })
        let cop = round3(received.reduce(0) { $0 + ($1.amountCop ?? 0) })
        response.months[slot].incomeUsd = usd
        response.months[slot].incomeCop = cop
        response.months[slot].usdCop = usd > 0 ? ((cop / usd) * 100).rounded() / 100 : 0
        summarize(&response.months[slot])
        response.annual = annual(from: response.months, keeping: response.annual)
    }

    private static func round3(_ value: Double) -> Double {
        (value * 1000).rounded() / 1000
    }

    static func applying(
        _ changes: [String: Outbox.PendingValue],
        to entry: Entry,
        in response: DashboardResponse
    ) -> DashboardResponse {
        guard let monthIndex = response.months.firstIndex(where: { month in
            month.entries.contains { sameEntry($0, entry) }
        }) else { return response }
        var updated = response
        var month = updated.months[monthIndex]
        guard let entryIndex = month.entries.firstIndex(where: { sameEntry($0, entry) }) else {
            return response
        }

        var target = month.entries[entryIndex]
        for (field, value) in changes {
            switch (field, value) {
            case ("description", .text(let text)): target.description = text
            case ("category", .text(let text)): target.category = text
            case ("target_type", .text(let text)): target.type = text
            case ("amount_cop", .number(let amount)): target.amountCop = amount
            case ("paid", .flag(let flag)): target.paid = flag
            case ("linked_debts", .list(let ids)): target.linkedDebts = ids
            case ("extra_payment", .flag(let flag)): target.extraPayment = flag
            default: break
            }
        }
        target.amountUsd = month.usdCop > 0 ? displayUsd(target.amountCop / month.usdCop) : 0
        month.entries[entryIndex] = target

        summarize(&month)
        updated.months[monthIndex] = month
        updated.annual = annual(from: updated.months, keeping: updated.annual)
        return updated
    }

    /// Un movimiento nuevo en el demo: nace con id propio, cae al final de
    /// su tipo — o justo después del original cuando es un duplicado — y el
    /// mes y el anual se re-agregan igual que en el servidor.
    static func creating(
        _ fields: [String: Outbox.PendingValue],
        monthIndex: Int,
        after original: Entry?,
        in response: DashboardResponse
    ) -> DashboardResponse {
        guard let position = response.months.firstIndex(where: { $0.index == monthIndex }) else {
            return response
        }
        var updated = response
        var month = updated.months[position]

        var description = ""
        if case .text(let text)? = fields["description"] { description = text }
        var category: String?
        if case .text(let text)? = fields["category"], !text.isEmpty { category = text }
        var type = "needs"
        if case .text(let text)? = fields["type"], !text.isEmpty { type = text }
        var amount = 0.0
        if case .number(let value)? = fields["amount_cop"] { amount = value }
        var paid = false
        if case .flag(let value)? = fields["paid"] { paid = value }
        var linkedDebts: [String]?
        if case .list(let ids)? = fields["linked_debts"], !ids.isEmpty { linkedDebts = ids }
        var extraPayment: Bool?
        if case .flag(let value)? = fields["extra_payment"] { extraPayment = value }

        let nextId = (updated.months.flatMap(\.entries).compactMap(\.entryId).max() ?? 0) + 1
        let entry = Entry(
            description: description,
            category: category,
            amountCop: amount,
            amountUsd: month.usdCop > 0 ? displayUsd(amount / month.usdCop) : 0,
            type: type,
            paid: paid,
            active: nil,
            sourcePath: original?.sourcePath ?? month.entries.first?.sourcePath ?? month.sourcePathByType?[type],
            sourceIndex: month.entries.count,
            entryId: nextId,
            autoGenerated: nil,
            linkedDebts: linkedDebts,
            extraPayment: extraPayment,
            createdAt: nil,
            updatedAt: nil,
            history: []
        )

        if let original, let originalIndex = month.entries.firstIndex(where: { sameEntry($0, original) }) {
            month.entries.insert(entry, at: originalIndex + 1)
        } else if let lastOfType = month.entries.lastIndex(where: { ($0.type ?? "needs") == type }) {
            month.entries.insert(entry, at: lastOfType + 1)
        } else {
            month.entries.append(entry)
        }

        summarize(&month)
        updated.months[position] = month
        updated.annual = annual(from: updated.months, keeping: updated.annual)
        return updated
    }

    /// Borrar en el demo: fuera el movimiento, y a re-agregar mes y anual.
    static func deleting(_ entry: Entry, in response: DashboardResponse) -> DashboardResponse {
        guard let position = response.months.firstIndex(where: { month in
            month.entries.contains { sameEntry($0, entry) }
        }) else { return response }
        var updated = response
        var month = updated.months[position]
        month.entries.removeAll { sameEntry($0, entry) }
        summarize(&month)
        updated.months[position] = month
        updated.annual = annual(from: updated.months, keeping: updated.annual)
        return updated
    }

    /// La identidad del movimiento: el id permanente, o ruta|índice.
    private static func sameEntry(_ a: Entry, _ b: Entry) -> Bool {
        if let left = a.entryId, let right = b.entryId { return left == right }
        return a.sourcePath != nil && a.sourcePath == b.sourcePath && a.sourceIndex == b.sourceIndex
    }

    /// _summarize_month: totales, tipos, categorías, la tabla de resumen y el
    /// "Free" que se enseña como deseos cuando el mes queda en verde.
    private static func summarize(_ month: inout MonthSummary) {
        var byType: [String: Double] = ["debts": 0, "needs": 0, "savings": 0, "wants": 0]
        var byCategory: [String: Double] = [:]
        var total = 0.0
        var paid = 0.0

        for entry in month.entries {
            let value = displayCop(entry.amountCop)
            total += value
            if entry.isPaid { paid += value }
            var type = (entry.type ?? "").trimmingCharacters(in: .whitespaces).lowercased()
            if byType[type] == nil { type = "needs" }
            byType[type, default: 0] += value
            let category = (entry.category ?? "").trimmingCharacters(in: .whitespaces)
            byCategory[category.isEmpty ? "—" : category, default: 0] += value
        }

        month.totalOutcomes = displayCop(total)
        month.paidOutcomes = displayCop(paid)
        byType = byType.mapValues(displayCop)
        byCategory = byCategory.mapValues(displayCop)
        month.free = displayCop(month.incomeCop - month.totalOutcomes)
        month.afterPaid = displayCop(month.incomeCop - month.paidOutcomes)

        var displayTypes = byType
        if month.free > 0 {
            displayTypes["wants", default: 0] += month.free
            byCategory["Free", default: 0] += month.free
        }
        month.byType = byType
        month.displayTypes = displayTypes
        month.byCategory = byCategory
            .map { CategoryTotal(category: $0.key, total: $0.value) }
            .sorted { $0.total > $1.total }

        let usdCop = month.usdCop
        let incomeCop = month.incomeCop
        func row(_ label: String, _ value: Double) -> SummaryRow {
            SummaryRow(
                label: label,
                cop: value,
                usd: usdCop > 0 ? displayUsd(value / usdCop) : 0,
                ratio: incomeCop > 0 ? value / incomeCop * 100 : 0
            )
        }
        var rows = [SummaryRow(label: "incomes", cop: incomeCop, usd: month.incomeUsd, ratio: 100)]
        for key in ["savings", "needs", "wants", "debts"] {
            rows.append(row(key, displayTypes[key] ?? 0))
        }
        rows.append(row("after_paid", month.afterPaid ?? 0))
        if month.free < 0 {
            rows.append(row("deficit", abs(month.free)))
        }
        month.summaryRows = rows
    }

    /// La parte anual de _build_dashboard: sumas de los meses, y en dólares
    /// cada mes convierte con su propia tasa antes de sumar.
    private static func annual(from months: [MonthSummary], keeping previous: AnnualSummary?) -> AnnualSummary? {
        guard let previous else { return nil }
        var byType: [String: Double] = ["debts": 0, "needs": 0, "savings": 0, "wants": 0]
        var displayTypes = byType
        var byCategory: [String: Double] = [:]
        for month in months {
            for (key, value) in month.byType { byType[key, default: 0] += value }
            for (key, value) in month.displayTypes { displayTypes[key, default: 0] += value }
            for item in month.byCategory { byCategory[item.category, default: 0] += item.total }
        }

        func metric(_ pick: (MonthSummary) -> Double) -> Money {
            Money(
                cop: displayCop(months.reduce(0) { $0 + pick($1) }),
                usd: displayUsd(
                    months.filter { $0.usdCop > 0 }.reduce(0) { $0 + pick($1) / $1.usdCop }
                )
            )
        }

        var annual = previous
        annual.totalOutcomes = displayCop(months.reduce(0) { $0 + $1.totalOutcomes })
        annual.free = displayCop(months.reduce(0) { $0 + $1.free })
        annual.averageFree = displayCop(annual.free / Double(max(months.count, 1)))
        annual.byType = byType.mapValues(displayCop)
        annual.displayTypes = displayTypes.mapValues(displayCop)
        annual.byCategory = byCategory
            .map { CategoryTotal(category: $0.key, total: displayCop($0.value)) }
            .sorted { $0.total > $1.total }
        annual.totals = [
            "income": metric { $0.incomeCop },
            "outcomes": metric { $0.totalOutcomes },
            "free": metric { $0.free },
            "needs": metric { $0.byType["needs"] ?? 0 },
            "wants": metric { $0.displayTypes["wants"] ?? 0 },
            "savings": metric { $0.byType["savings"] ?? 0 },
            "debts": metric { $0.byType["debts"] ?? 0 },
        ]
        return annual
    }
}
