import Foundation

/// Lo que contesta GET /api/dashboard: un año ya agregado por server.py.
/// La app no suma nada por su cuenta — la misma regla que el cliente web:
/// toda la aritmética vive en el servidor y los clientes solo pintan.
struct DashboardResponse: Decodable {
    let ok: Bool
    let years: [String]
    let year: String
    /// var: el demo edita en memoria y DemoMath re-agrega estas piezas.
    var months: [MonthSummary]
    var annual: AnnualSummary?
}

/// mobile/dashboard.json: todos los años ya calculados por el servidor y
/// sincronizados por iCloud. Cada entrada es la misma respuesta de
/// /api/dashboard, así que el resto de la app no distingue la fuente.
struct MobileSnapshot: Decodable {
    let generatedAt: String?
    let years: [String]
    let dashboards: [String: DashboardResponse]
    /// El dataset de muestra: enseñar la app sin enseñar las finanzas.
    let demo: SnapshotDataset?
    /// El catálogo compartido de categorías, para el selector del modal de
    /// edición. Opcional: un snapshot viejo simplemente no lo trae.
    let categories: [String]?
}

struct SnapshotDataset: Decodable {
    let years: [String]
    let dashboards: [String: DashboardResponse]
}

/// mobile/manifest.json: el índice del snapshot partido por año — qué años
/// hay, el catálogo de categorías y el sello de cada año. Con esto la app
/// decide qué archivo abrir sin descargar ni decodificar nada grande.
struct SnapshotManifest: Decodable {
    let generatedAt: String?
    let years: [String]
    let categories: [String]?
    let yearStamps: [String: String]?
}

struct AnnualSummary: Decodable {
    let incomeCop: Double
    let incomeUsd: Double
    var totalOutcomes: Double
    var free: Double
    var averageFree: Double
    let averageFx: Double
    /// "36 categorías registradas": el catálogo compartido, no las usadas.
    let categoriesCount: Int?
    var byType: [String: Double]
    var displayTypes: [String: Double]
    var byCategory: [CategoryTotal]
    var totals: [String: Money]
}

struct Money: Decodable {
    let cop: Double
    let usd: Double
}

struct CategoryTotal: Decodable, Identifiable {
    let category: String
    let total: Double
    var id: String { category }
}

struct MonthSummary: Decodable, Identifiable {
    let index: Int
    let folder: String
    let incomeCop: Double
    let incomeUsd: Double
    let usdCop: Double
    var totalOutcomes: Double
    var paidOutcomes: Double
    var free: Double
    /// Opcionales por si contesta un servidor viejo: mejor una tabla con
    /// filas de menos que una pantalla en blanco (misma decisión que load.ts).
    var afterPaid: Double?
    var summaryRows: [SummaryRow]?
    var byType: [String: Double]
    var displayTypes: [String: Double]
    var byCategory: [CategoryTotal]
    var entries: [Entry]
    let incomes: [Income]

    var id: Int { index }
    var rows: [SummaryRow] { summaryRows ?? [] }
}

struct SummaryRow: Decodable, Identifiable {
    let label: String
    let cop: Double
    let usd: Double
    let ratio: Double
    var id: String { label }
}

struct Entry: Decodable, Identifiable {
    var id = UUID()
    var description: String?
    var category: String?
    var amountCop: Double
    var amountUsd: Double?
    var type: String?
    var paid: Bool?
    /// La bandera vieja de pagado, presente en archivos anteriores.
    let active: Bool?
    /// De dónde salió el movimiento — lo que el buzón necesita para pedirle
    /// al servidor del Mac que lo cambie.
    let sourcePath: String?
    let sourceIndex: Int?
    /// El id permanente y numérico que el servidor le asigna: encuentra el
    /// movimiento aunque la lista se reordene.
    let entryId: Int?
    /// true en las cuotas que nacen de una deuda: de esas solo se puede
    /// tocar el pagado — la edición vive en la deuda.
    let autoGenerated: Bool?

    var isPaid: Bool { paid ?? active ?? false }

    private enum CodingKeys: String, CodingKey {
        case description, category, amountCop, amountUsd, type, paid, active
        case sourcePath, sourceIndex, autoGenerated
        case entryId = "id"
    }
}

struct Income: Decodable, Identifiable {
    var id = UUID()
    let description: String?
    let amountUsd: Double?
    let usdCop: Double?
    let amountCop: Double?
    let received: Bool?

    private enum CodingKeys: String, CodingKey {
        case description, amountUsd, usdCop, amountCop, received
    }
}

/// La aritmética del demo — la única excepción a "toda la aritmética vive en
/// el servidor". El demo va empacado en la app y no tiene Mac atrás, así que
/// editar un movimiento re-agrega aquí el mes y el anual, espejando
/// _summarize_month y _build_dashboard de server.py con sus mismos redondeos
/// (display_cop / display_usd). Solo el demo pasa por aquí; el live sigue
/// pintando lo que el servidor calculó.
enum DemoMath {
    /// normalizeCop del servidor: pesos enteros, mitades hacia arriba.
    private static func displayCop(_ value: Double) -> Double {
        guard value.isFinite, abs(value) >= 0.5 else { return 0 }
        return (value + 0.5).rounded(.down)
    }

    /// normalizeUsd: dos decimales, mitades hacia arriba como JavaScript.
    private static func displayUsd(_ value: Double) -> Double {
        guard value.isFinite, abs(value) >= 0.005 else { return 0 }
        return (value * 100 + 0.5).rounded(.down) / 100
    }

    /// Aplica los cambios (las mismas claves que viajan al buzón del live:
    /// description, category, target_type, amount_cop, paid) y devuelve la
    /// respuesta con el mes tocado y el anual ya re-agregados.
    static func applying(
        _ changes: [String: Outbox.PendingValue],
        to entry: Entry,
        in response: DashboardResponse
    ) -> DashboardResponse {
        guard let monthIndex = response.months.firstIndex(where: { month in
            month.entries.contains { sameEntry($0, entry) }
        }) else { return response }
        var updated = response
        var month = updated.months[monthIndex]
        guard let entryIndex = month.entries.firstIndex(where: { sameEntry($0, entry) }) else {
            return response
        }

        var target = month.entries[entryIndex]
        for (field, value) in changes {
            switch (field, value) {
            case ("description", .text(let text)): target.description = text
            case ("category", .text(let text)): target.category = text
            case ("target_type", .text(let text)): target.type = text
            case ("amount_cop", .number(let amount)): target.amountCop = amount
            case ("paid", .flag(let flag)): target.paid = flag
            default: break
            }
        }
        target.amountUsd = month.usdCop > 0 ? displayUsd(target.amountCop / month.usdCop) : 0
        month.entries[entryIndex] = target

        summarize(&month)
        updated.months[monthIndex] = month
        updated.annual = annual(from: updated.months, keeping: updated.annual)
        return updated
    }

    /// La identidad del movimiento: el id permanente, o ruta|índice.
    private static func sameEntry(_ a: Entry, _ b: Entry) -> Bool {
        if let left = a.entryId, let right = b.entryId { return left == right }
        return a.sourcePath != nil && a.sourcePath == b.sourcePath && a.sourceIndex == b.sourceIndex
    }

    /// _summarize_month: totales, tipos, categorías, la tabla de resumen y el
    /// "Free" que se enseña como deseos cuando el mes queda en verde.
    private static func summarize(_ month: inout MonthSummary) {
        var byType: [String: Double] = ["debts": 0, "needs": 0, "savings": 0, "wants": 0]
        var byCategory: [String: Double] = [:]
        var total = 0.0
        var paid = 0.0

        for entry in month.entries {
            let value = displayCop(entry.amountCop)
            total += value
            if entry.isPaid { paid += value }
            var type = (entry.type ?? "").trimmingCharacters(in: .whitespaces).lowercased()
            if byType[type] == nil { type = "needs" }
            byType[type, default: 0] += value
            let category = (entry.category ?? "").trimmingCharacters(in: .whitespaces)
            byCategory[category.isEmpty ? "—" : category, default: 0] += value
        }

        month.totalOutcomes = displayCop(total)
        month.paidOutcomes = displayCop(paid)
        byType = byType.mapValues(displayCop)
        byCategory = byCategory.mapValues(displayCop)
        month.free = displayCop(month.incomeCop - month.totalOutcomes)
        month.afterPaid = displayCop(month.incomeCop - month.paidOutcomes)

        var displayTypes = byType
        if month.free > 0 {
            displayTypes["wants", default: 0] += month.free
            byCategory["Free", default: 0] += month.free
        }
        month.byType = byType
        month.displayTypes = displayTypes
        month.byCategory = byCategory
            .map { CategoryTotal(category: $0.key, total: $0.value) }
            .sorted { $0.total > $1.total }

        let usdCop = month.usdCop
        let incomeCop = month.incomeCop
        func row(_ label: String, _ value: Double) -> SummaryRow {
            SummaryRow(
                label: label,
                cop: value,
                usd: usdCop > 0 ? displayUsd(value / usdCop) : 0,
                ratio: incomeCop > 0 ? value / incomeCop * 100 : 0
            )
        }
        var rows = [SummaryRow(label: "incomes", cop: incomeCop, usd: month.incomeUsd, ratio: 100)]
        for key in ["savings", "needs", "wants", "debts"] {
            rows.append(row(key, displayTypes[key] ?? 0))
        }
        rows.append(row("after_paid", month.afterPaid ?? 0))
        if month.free < 0 {
            rows.append(row("deficit", abs(month.free)))
        }
        month.summaryRows = rows
    }

    /// La parte anual de _build_dashboard: sumas de los meses, y en dólares
    /// cada mes convierte con su propia tasa antes de sumar.
    private static func annual(from months: [MonthSummary], keeping previous: AnnualSummary?) -> AnnualSummary? {
        guard let previous else { return nil }
        var byType: [String: Double] = ["debts": 0, "needs": 0, "savings": 0, "wants": 0]
        var displayTypes = byType
        var byCategory: [String: Double] = [:]
        for month in months {
            for (key, value) in month.byType { byType[key, default: 0] += value }
            for (key, value) in month.displayTypes { displayTypes[key, default: 0] += value }
            for item in month.byCategory { byCategory[item.category, default: 0] += item.total }
        }

        func metric(_ pick: (MonthSummary) -> Double) -> Money {
            Money(
                cop: displayCop(months.reduce(0) { $0 + pick($1) }),
                usd: displayUsd(
                    months.filter { $0.usdCop > 0 }.reduce(0) { $0 + pick($1) / $1.usdCop }
                )
            )
        }

        var annual = previous
        annual.totalOutcomes = displayCop(months.reduce(0) { $0 + $1.totalOutcomes })
        annual.free = displayCop(months.reduce(0) { $0 + $1.free })
        annual.averageFree = displayCop(annual.free / Double(max(months.count, 1)))
        annual.byType = byType.mapValues(displayCop)
        annual.displayTypes = displayTypes.mapValues(displayCop)
        annual.byCategory = byCategory
            .map { CategoryTotal(category: $0.key, total: displayCop($0.value)) }
            .sorted { $0.total > $1.total }
        annual.totals = [
            "income": metric { $0.incomeCop },
            "outcomes": metric { $0.totalOutcomes },
            "free": metric { $0.free },
            "needs": metric { $0.byType["needs"] ?? 0 },
            "wants": metric { $0.displayTypes["wants"] ?? 0 },
            "savings": metric { $0.byType["savings"] ?? 0 },
            "debts": metric { $0.byType["debts"] ?? 0 },
        ]
        return annual
    }
}
